const DEFAULT_FLAT_FEE = Number(process.env.BILLING_FLAT_FEE) || 7500;
const DEFAULT_ELECTRICITY_RATE = Number(process.env.BILLING_ELEC_RATE) || 14;
const DEFAULT_DUE_DAYS_FROM_CREATION = 14;
const DEFAULT_GRACE_PERIOD_DAYS = Number(process.env.BILLING_GRACE_PERIOD_DAYS) || 5;

module.exports = { DEFAULT_FLAT_FEE, DEFAULT_ELECTRICITY_RATE, DEFAULT_DUE_DAYS_FROM_CREATION, DEFAULT_GRACE_PERIOD_DAYS };
